times = ("arsenal","city","manchester united","aston villa","liverpool","boumemouth","sunderland", "brighton","brentford","chelsea","fulhan","newcastle","everton","leeds","crystal palace","nottingham","spurs","west ham","burnley","wolves")
print('-=' * 20)     
print(f'Lista de times: {times}')
print('-=' * 20)
print(f'Os 5 primeiros são {times[0:5]}')
print('-=' * 20)
print(f'Os 4 últimos são {times[-4:]}')
print('-=' * 20)
print(f'Times em ordem alfabética A a Z: {sorted(times)}')
print('-=' * 20)
print(f'Times em ordem alfabética z a A: {sorted(times, reverse=True)}')
print('-=' * 20)
print(f'O Everton está na {times.index("everton")+ 1}° posição')

